# Generated by Django 3.1.1 on 2020-09-17 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('trumpSuit', models.CharField(choices=[('DI', 'DIAMOND'), ('SP', 'SPADE'), ('HE', 'HEART'), ('CL', 'CLUB')], default='SP', max_length=2)),
                ('SP_wt', models.IntegerField(default=10000)),
                ('DI_wt', models.IntegerField(default=200)),
                ('HE_wt', models.IntegerField(default=300)),
                ('CL_wt', models.IntegerField(default=400)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='court_peice.game')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.CharField(choices=[('DI', 'DIAMOND'), ('SP', 'SPADE'), ('HE', 'HEART'), ('CL', 'CLUB')], max_length=2)),
                ('rank', models.CharField(choices=[('A', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('X', '10'), ('J', '11'), ('Q', '12'), ('K', '13')], max_length=1)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='court_peice.game')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='court_peice.player')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.CharField(choices=[('DI', 'DIAMOND'), ('SP', 'SPADE'), ('HE', 'HEART'), ('CL', 'CLUB')], max_length=2)),
                ('rank', models.CharField(choices=[('A', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('X', '10'), ('J', '11'), ('Q', '12'), ('K', '13')], max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='court_peice.game')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='court_peice.player')),
            ],
        ),
    ]
