# Generated by Django 3.1.1 on 2020-09-17 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('court_peice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='court_peice.player'),
        ),
    ]
