# Generated by Django 3.1.1 on 2020-09-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court_peice', '0003_auto_20200918_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='strongSuit',
            field=models.CharField(choices=[('DI', 'DIAMOND'), ('SP', 'SPADE'), ('HE', 'HEART'), ('CL', 'CLUB')], default='SP', max_length=2),
            preserve_default=False,
        ),
    ]
